/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.EntradaControle;
import controle.FuncionarioControle;
import controle.ServicoControle;
import dominio.Excecao;
import dominio.Funcionario;
import dominio.Servico;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darlan
 */
public class Cad_Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Cad_Agenda
     */
    private FuncionarioControle funcControle;
    private ServicoControle servControle;
    private EntradaControle entControle;
    private Funcionario funcionario;
    private List<Funcionario>listafunc;
    private List<Servico>listaserv;
    private String dataBanco;
    private boolean altera;
    public Cad_Agenda() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.altera = false;
        SimpleDateFormat sp = new SimpleDateFormat("yyyy-MM-dd");
        dataBanco = sp.format(jcCalendario.getDate());
        funcControle = new FuncionarioControle();
        servControle = new ServicoControle();
        entControle = new EntradaControle();
        desabilitaCampos();
        carregaTabela();
        carregarFuncionarios();
       
      
    }

    public void carregaTabela(){
     DefaultTableModel modelo = (DefaultTableModel) tblAgenda.getModel();
         if(modelo.getRowCount()>0){
            modelo.setRowCount(0);
        }
         listaserv = servControle.retornaServicoData(dataBanco);
         
        for(Servico s:listaserv){
            Object[] o = new Object[6];
            o[0] = s.getData();
            o[1] = s.getHora();
            o[2] = s.getFuncionario().getNome();
            o[3] = s.getDescricao();
            o[4] = s.getValor();
            if(s.getPago()==1){
            o[5] = "SIM";
            }else{
           o[5] = "NÃO";

            }
            modelo.addRow(o);  
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        jcCalendario = new com.toedter.calendar.JCalendar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbFuncionario = new javax.swing.JComboBox();
        tfDescricao = new javax.swing.JTextField();
        tfValor = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jrSim = new javax.swing.JRadioButton();
        jrNao = new javax.swing.JRadioButton();
        btSalvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfdata = new javax.swing.JFormattedTextField();
        cbHora = new javax.swing.JComboBox();
        cbMinutos = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbTipoPgto = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btPago = new javax.swing.JButton();
        btSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agenda");

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Horário", "Funcionario", "Descrição", "Valor", "Pago"
            }
        ));
        tblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgenda);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jcCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcCalendarioMouseClicked(evt);
            }
        });
        jcCalendario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcCalendarioPropertyChange(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Agendar Serviço"));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Funcionário");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Horário");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Descrição");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Valor");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Pago");

        cbFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuncionarioActionPerformed(evt);
            }
        });

        tfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jLabel6.setText("R$");

        bgPago.add(jrSim);
        jrSim.setText("SIM");

        bgPago.add(jrNao);
        jrNao.setSelected(true);
        jrNao.setText("NÃO");

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/save-icon.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Data");

        tfdata.setEnabled(false);

        cbHora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        cbMinutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Hora");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Minutos");

        cbTipoPgto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dinheiro", "Cartão" }));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("Forma de pagamento");

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/adicionar.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/alterar.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/deletar.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/dinheiro.png"))); // NOI18N
        btPago.setText("Marcar como Pago");
        btPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAlterar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbTipoPgto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9))
                                .addComponent(tfValor)
                                .addComponent(tfdata)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jrSim)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jrNao)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPago))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jrSim)
                    .addComponent(jrNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btNovo)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir)
                    .addComponent(btPago))
                .addGap(45, 45, 45))
        );

        btSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/agenda.png"))); // NOI18N
        btSelecionar.setText("Selecionar Data");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btSelecionar)
                                .addGap(135, 135, 135)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jcCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSelecionar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
        if(!this.altera){
        String descricao = tfDescricao.getText();
        String data = tfdata.getText();
        String hora = cbHora.getSelectedItem()+":"+cbMinutos.getSelectedItem();
        String valor =  tfValor.getText();
        String pago = null;
        String tipo = cbTipoPgto.getSelectedItem().toString();
        String func = cbFuncionario.getSelectedItem().toString();
        funcionario = funcControle.buscaIdFuncionario(func);
        listaserv = servControle.retornaServicoData(dataBanco);
        if(jrSim.isSelected()){
        pago = "SIM";
        int pg = 1;
            try {
                servControle.salvarServico(descricao, valor, pago, data, hora, tipo, funcionario);
                String desc = descricao+" Funcionario: "+func;
                entControle.salvarEntrada(desc, data, valor, pg , tipo);
                carregaTabela();
                desabilitaCampos();
            } catch (Excecao ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }   catch (Exception ex) {
               JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
        }else{
        pago = "NÃO";
        
        try {
            servControle.salvarServico(descricao, valor, pago, data, hora,tipo, funcionario);
              carregaTabela();
              desabilitaCampos();
               
        } catch (Excecao ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } 
        this.altera = false;    
        }    
        }else{
        
        String descricao = tfDescricao.getText();
        String data = tfdata.getText();
        String hora = cbHora.getSelectedItem()+":"+cbMinutos.getSelectedItem();
        String valor =  tfValor.getText();
        String pago = null;
        String tipo = cbTipoPgto.getSelectedItem().toString();
        String func = cbFuncionario.getSelectedItem().toString();
        funcionario = funcControle.buscaIdFuncionario(func);
        listaserv = servControle.retornaServicoData(dataBanco);
        int pos = tblAgenda.getSelectedRow();
        listaserv = servControle.retornaServicoData(dataBanco);
        Servico servico = listaserv.get(pos);
        
        if(jrSim.isSelected()){
        pago = "SIM";
        
        }else{
        
            pago = "NÃO";
        
        }
        try {
            servControle.alterarServico(servico.getId(),descricao, valor, pago, data, hora,tipo, funcionario);
              carregaTabela();
              desabilitaCampos();
               
        } catch (Excecao ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } 
        
        this.altera = false;    
              
        }
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void jcCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcCalendarioMouseClicked
        

// TODO add your handling code here:
    }//GEN-LAST:event_jcCalendarioMouseClicked

    private void jcCalendarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcCalendarioPropertyChange
        
// TODO add your handling code here:
    }//GEN-LAST:event_jcCalendarioPropertyChange

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        SimpleDateFormat sp = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sp1 = new SimpleDateFormat("dd/MM/yyyy");
        String data = sp1.format(jcCalendario.getDate());
        this.dataBanco = sp.format(jcCalendario.getDate());
        tfdata.setText(data);
        
        carregaTabela();
    }//GEN-LAST:event_btSelecionarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
      habilitaCampos();
      this.altera = true;
     
    }//GEN-LAST:event_btAlterarActionPerformed

    private void tblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendaMouseClicked
        
        int pos = tblAgenda.getSelectedRow();
        int sel,selMin,selFunc,selTipo;
        sel = selMin = selFunc = selTipo =  0;
        listaserv = servControle.retornaServicoData(dataBanco);
        cbFuncionario.setSelectedItem(listaserv.get(pos));
        tfDescricao.setText(listaserv.get(pos).getDescricao());
        tfValor.setText(listaserv.get(pos).getValor().toString());
        if(listaserv.get(pos).getPago()== 1){
            jrSim.setSelected(true);
            jrNao.setSelected(false);
            btPago.setEnabled(false);
        }else{
            jrNao.setSelected(true);
            jrSim.setSelected(false);
            btPago.setEnabled(true);
        }
        for(int i=0;i<cbHora.getItemCount();i++){
          cbHora.setSelectedIndex(i);
          String hora = cbHora.getSelectedItem().toString();
          if(listaserv.get(pos).getHora().substring(0,2).equals(hora)){
               sel = i;
          }      
          cbHora.setSelectedIndex(sel);
        }
        for(int i=0;i<cbMinutos.getItemCount();i++){
          cbMinutos.setSelectedIndex(i);
          String hora = cbMinutos.getSelectedItem().toString();
          if(listaserv.get(pos).getHora().substring(3,5).equals(hora)){
               selMin = i;
          }      
            cbMinutos.setSelectedIndex(selMin);
        }
        for(int i = 0;i<cbFuncionario.getItemCount();i++){
            cbFuncionario.setSelectedIndex(i);
            String func = cbFuncionario.getSelectedItem().toString();
            if(listaserv.get(pos).getFuncionario().getNome().equals(func)){
                selFunc = i;
            }else{
                selFunc = 0;
            }
            cbFuncionario.setSelectedIndex(selFunc);
        }
        for(int i = 0;i<cbTipoPgto.getItemCount();i++){
            listaserv = servControle.retornaServicoData(dataBanco);
            cbTipoPgto.setSelectedIndex(i);
            String tipo = cbTipoPgto.getSelectedItem().toString();
            if(listaserv.get(pos).getTipo_pgto().equals(tipo)){
                selTipo = i;
            }
            cbTipoPgto.setSelectedIndex(selTipo);
        }
        SimpleDateFormat sp1 = new SimpleDateFormat("dd/MM/yyyy");
        String data = sp1.format(jcCalendario.getDate());
        tfdata.setText(data);
        
    }//GEN-LAST:event_tblAgendaMouseClicked

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
     habilitaCampos();
     limpaCampos();
     this.altera = false;
    }//GEN-LAST:event_btNovoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
     int pos = tblAgenda.getSelectedRow();
     listaserv = servControle.retornaServicoData(dataBanco);
     servControle.apagarServico(listaserv.get(pos));
       carregaTabela();
       limpaCampos();

    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagoActionPerformed
            
        String descricao = tfDescricao.getText();
        String data = tfdata.getText();
        String hora = cbHora.getSelectedItem()+":"+cbMinutos.getSelectedItem();
        String valor =  tfValor.getText();
        String pago = null;
        
        String tipo = cbTipoPgto.getSelectedItem().toString();
        String func = cbFuncionario.getSelectedItem().toString();
        funcionario = funcControle.buscaIdFuncionario(func);
        listaserv = servControle.retornaServicoData(dataBanco);
        pago = "SIM";
        int pg = 1;
            try {
                Date datasistema = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                datasistema.getTime();
                String datasis = sdf.format(datasistema);
                String desc = descricao+" Funcionario: "+func;
                entControle.salvarEntrada(desc, datasis, valor, pg , tipo);
            } catch (Excecao ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            }   catch (Exception ex) {
               JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        try {
            listaserv = servControle.retornaServicoData(dataBanco);
            int pos = tblAgenda.getSelectedRow();
            Servico servico = listaserv.get(pos);
            servControle.alterarServico(servico.getId(), descricao, valor, pago, data, hora, tipo, funcionario);
            carregaTabela();
            desabilitaCampos();
        } catch (Excecao ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            }
    }//GEN-LAST:event_btPagoActionPerformed

    private void cbFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFuncionarioActionPerformed
    public void carregarFuncionarios(){
    listafunc = funcControle.listarFuncionarios();
    for(Funcionario f:listafunc){
        cbFuncionario.addItem(f.getNome());
    }
        
    }
    
    public void desabilitaCampos(){
    cbFuncionario.setEnabled(false);
    cbHora.setEnabled(false);
    cbMinutos.setEnabled(false);
    cbTipoPgto.setEnabled(false);
    tfDescricao.setEnabled(false);
    tfValor.setEnabled(false);
    jrNao.setEnabled(false);
    jrSim.setEnabled(false);
}
    public void habilitaCampos(){
    cbFuncionario.setEnabled(true);
    cbHora.setEnabled(true);
    cbMinutos.setEnabled(true);
    cbTipoPgto.setEnabled(true);
    tfDescricao.setEnabled(true);
    tfValor.setEnabled(true);
    jrNao.setEnabled(true);
    jrSim.setEnabled(true);
}
    public void limpaCampos(){
        cbFuncionario.setSelectedIndex(0);
    cbHora.setSelectedIndex(0);
    cbMinutos.setSelectedIndex(0);
    cbTipoPgto.setSelectedIndex(0);
    tfDescricao.setText("");
    tfValor.setText("");
    tfdata.setText("");
    cbHora.setSelectedIndex(0);
    cbMinutos.setSelectedIndex(0);
    jrNao.setSelected(true);
    jrSim.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPago;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPago;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JComboBox cbFuncionario;
    private javax.swing.JComboBox cbHora;
    private javax.swing.JComboBox cbMinutos;
    private javax.swing.JComboBox cbTipoPgto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JCalendar jcCalendario;
    private javax.swing.JRadioButton jrNao;
    private javax.swing.JRadioButton jrSim;
    private javax.swing.JTable tblAgenda;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JFormattedTextField tfValor;
    private javax.swing.JFormattedTextField tfdata;
    // End of variables declaration//GEN-END:variables
}
