/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Programa;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import visao.Principal.hora;

/**
 *
 * @author darlan
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private Programa programa;
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        programa = new Programa();
        Date data = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        data.getTime();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        btnAgenda = new javax.swing.JButton();
        btAbreCaixa = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        btConsultaCaixa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btFechamentoFunc = new javax.swing.JButton();
        lbdata = new javax.swing.JLabel();
        btAterarCaixa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbhora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salão da Danny");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Principal"));

        btnAgenda.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/agenda.png"))); // NOI18N
        btnAgenda.setText("Agenda");
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });

        btAbreCaixa.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btAbreCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/abrecaixa.png"))); // NOI18N
        btAbreCaixa.setText("Abrir Caixa");
        btAbreCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbreCaixaActionPerformed(evt);
            }
        });

        btnFuncionario.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/funcionario.png"))); // NOI18N
        btnFuncionario.setText("Cadastro de Funcionários");
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });

        btConsultaCaixa.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btConsultaCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/alteracaixa.png"))); // NOI18N
        btConsultaCaixa.setText("Consultar Caixa");
        btConsultaCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaCaixaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/movimentarcaixa.png"))); // NOI18N
        jButton1.setText("Movimentar Caixa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btFechamentoFunc.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btFechamentoFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/fechamento.png"))); // NOI18N
        btFechamentoFunc.setText("Fechamento ");
        btFechamentoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechamentoFuncActionPerformed(evt);
            }
        });

        lbdata.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lbdata.setText("data");

        btAterarCaixa.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btAterarCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/alterarCaixa.png"))); // NOI18N
        btAterarCaixa.setText("Alterar Caixa");
        btAterarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAterarCaixaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/Girls-Red-Dress-icon.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        lbhora.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lbhora.setText("hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbhora)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btAbreCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btConsultaCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(btAterarCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btFechamentoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lbdata))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAbreCaixa)
                            .addComponent(jButton1)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultaCaixa)
                    .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFechamentoFunc)
                    .addComponent(btAterarCaixa))
                .addGap(42, 42, 42)
                .addComponent(lbdata)
                .addGap(18, 18, 18)
                .addComponent(lbhora)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("DialogInput", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Salão da Danny");

        label1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        label1.setText("Desenvolvido por Darlan Falcão");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAbreCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbreCaixaActionPerformed
       programa.chamaCaixa();
    }//GEN-LAST:event_btAbreCaixaActionPerformed

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
     programa.chamaCadFuncionario();   // TODO add your handling code here:
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        programa.chamaVisaoCaixa();
        
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private void btConsultaCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaCaixaActionPerformed
       programa.chamaConsultaCaixa();
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultaCaixaActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
    programa.chamaCadAgenda();
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btFechamentoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechamentoFuncActionPerformed
        programa.chamaFechamentoFunc();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btFechamentoFuncActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
  Date datasistema = new Date();
  SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
  lbdata.setText(formato.format(datasistema));
  Timer timer = new Timer(1000, new hora());
  timer.start();

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btAterarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAterarCaixaActionPerformed

        programa.chamaAlteraCaixa();

// TODO add your handling code here:
    }//GEN-LAST:event_btAterarCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbreCaixa;
    private javax.swing.JButton btAterarCaixa;
    private javax.swing.JButton btConsultaCaixa;
    private javax.swing.JButton btFechamentoFunc;
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private javax.swing.JLabel lbdata;
    private javax.swing.JLabel lbhora;
    // End of variables declaration//GEN-END:variables

   
    class hora implements ActionListener{
       
        public void actionPerfomed(ActionEvent e){
            Calendar now = Calendar.getInstance();
            lbhora.setText(String.format("%1$tH:%1$tM:%1$ts", now));
        }   

        @Override
        public void actionPerformed(ActionEvent e) {
           Calendar now = Calendar.getInstance();
            lbhora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
    
    }
    

